### PR TITLE
Partition the impressions table with pg_partman

### PR DESCRIPTION
**Pull request by jayzes**
Use daily partitions based on `created_at`. Existing queries should continue to work just fine. Long-term, the materialized views may not be needed.

- Provide a rake task to download/compile pg_partman (`db:partman:compile`)
- Convert schema to SQL
- Provide a task (`db:partman:run_maintenance`) to be run hourly for management

### CODE REVIEW

**Comment by jayzes** [comment]
Pushed up to staging and tested, and everything looks good there. Only weirdness is that I can't seem to be constraint exclusion working for any of the analytic queries, though. Even without that, the performance improvement seems to be solid, so I'm inclined to ship it to prod.

**Comment by jayzes** [comment]
Nevermind, got constraint exclusion working - just needed non-functional parameters:

```
ello-grandstand-stage::DATABASE=> explain analyze select count(1) from impressions where created_at between (date '2016-11-30') AND (date '2016-11-30' + interval '1 day'); 
                                                                                            QUERY PLAN                                                                                             
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=19.83..19.83 rows=1 width=0) (actual time=0.595..0.595 rows=1 loops=1)
   ->  Append  (cost=0.00..19.08 rows=1506 width=0) (actual time=0.008..0.482 rows=1504 loops=1)
         ->  Seq Scan on impressions  (cost=0.00..0.00 rows=1 width=0) (actual time=0.000..0.000 rows=0 loops=1)
               Filter: ((created_at >= '2016-11-30'::date) AND (created_at <= '2016-12-01 00:00:00'::timestamp without time zone))
         ->  Seq Scan on impressions_p2016_11_30  (cost=0.00..15.02 rows=1504 width=0) (actual time=0.008..0.359 rows=1504 loops=1)
               Filter: ((created_at >= '2016-11-30'::date) AND (created_at <= '2016-12-01 00:00:00'::timestamp without time zone))
         ->  Index Only Scan using impressions_p2016_12_01_created_at_author_id_post_id_idx on impressions_p2016_12_01  (cost=0.06..4.06 rows=1 width=0) (actual time=0.019..0.019 rows=0 loops=1)
               Index Cond: ((created_at >= '2016-11-30'::date) AND (created_at <= '2016-12-01 00:00:00'::timestamp without time zone))
               Heap Fetches: 0
 Planning time: 1.849 ms
 Execution time: 0.631 ms
(11 rows)
```

**Comment by jayzes** [comment]
Exactly - it just manages the triggers and child table creation for you (including replicating indices). It's [Heroku's recommended solution](https://devcenter.heroku.com/articles/increasing-performance-of-large-tables-using-partitioning) so I think it's pretty stable, and I didn't see a lot of value in re-implementing it ourselves from scratch.

**Comment by alanpeabody** [comment]
👍

**Pull request merged**
